# 编译类型
type: vue

# 名称
name: {{ .Name }}

# 镜像编译参数
docker:
  # 镜像名称
  image: {{ .DockerHub }}{{ .Name }}
  # 镜像编译文件(默认：Dockerfile)
  file: Dockerfile

# 服务定义
service:
  # 端口定义
  ports:
  - 9301:80

  # 环境变量
  envs:
  - TZ=Asia/Shanghai

  # 心跳检查
  healthcheck:
    url: /health
    interval: 10s
    timeout: 10s
    period: 30s
    retries: 30

  # 路由定义
  ingress:
  - backend-port: 80
    strip-path: true
    sso:
    - {{ .BasePath }}
