// Code generated by rice embed-go; DO NOT EDIT.
package utils

import (
	"time"

	"github.com/GeertJohan/go.rice/embedded"
)

func init() {

	// define files
	file2 := &embedded.EmbeddedFile{
		Filename:    "COMMITID",
		FileModTime: time.Unix(1756720188, 0),

		Content: string("1c118940b5a860315eb78f197887a86edaaceafb"),
	}
	file3 := &embedded.EmbeddedFile{
		Filename:    "VERSION",
		FileModTime: time.Unix(1756720188, 0),

		Content: string("1.2.27"),
	}

	// define dirs
	dir1 := &embedded.EmbeddedDir{
		Filename:   "",
		DirModTime: time.Unix(1756132985, 0),
		ChildFiles: []*embedded.EmbeddedFile{
			file2, // "COMMITID"
			file3, // "VERSION"

		},
	}

	// link ChildDirs
	dir1.ChildDirs = []*embedded.EmbeddedDir{}

	// register embeddedBox
	embedded.RegisterEmbeddedBox(`../asset/version`, &embedded.EmbeddedBox{
		Name: `../asset/version`,
		Time: time.Unix(1756132985, 0),
		Dirs: map[string]*embedded.EmbeddedDir{
			"": dir1,
		},
		Files: map[string]*embedded.EmbeddedFile{
			"COMMITID": file2,
			"VERSION":  file3,
		},
	})
}
