pipeline {
  agent {
    node {
      label "maven"
    }
  }
  parameters {
    string(name: 'REPO_SECRET', defaultValue: 'nexus-id', description: '发布仓库密钥')
    string(name: 'K8S_SECRET', defaultValue: 'k8s-id', description: 'K8s部署密钥')
    string(name: 'K8S_NAMESPACE', defaultValue: 'test', description: 'K8s部署名字空间/项目')
    string(name: 'K8S_PULLIMAGE_SECRET', defaultValue: 'pull-image-secret', description: 'K8s拉取镜像密钥名称')
    string(name: 'JWT_TOKEN', defaultValue: '', description: 'API授权令牌')
    string(name: 'JWT_PRIVKEY', defaultValue: '', description: 'API访问私钥')
    string(name: 'JDBC_URL', defaultValue: 'jdbc:postgresql://postgres:5432/demo', description: 'JDBC连接地址')
    string(name: 'JDBC_USER', defaultValue: 'postgres', description: 'JDBC访问用户')
    string(name: 'JDBC_PASSWORD', defaultValue: 'snz1dp9527', description: 'JDBC访问密码')
    string(name: 'REDIS_SERVER', defaultValue: 'redis:6379', description: 'REDIS服务地址')
    string(name: 'REDIS_PASSWORD', defaultValue: 'snz1dp9527', description: 'REDIS访问密码')
    string(name: 'REDIS_DB', defaultValue: '6', description: 'REDIS数据库索引')
    string(name: 'CONFIG_URL', defaultValue: 'http://confserv/appconfig', description: '动态配置服务URL地址')
    string(name: 'XEAI_URL', defaultValue: 'http://xeai/xeai', description: '认证服务URL地址')
    string(name: 'INITIAL_USERNAME', defaultValue: 'root', description: '初始化用户名')
    string(name: 'INITIAL_PASSWORD', defaultValue: '123456', description: '初始化用户密码')
  }
  environment {
    REPO_SECRET = "${params.REPO_SECRET}"
    KUBECONFIG_CREDENTIAL_ID = "${params.K8S_SECRET}"
    DEPLOY_NAMESPACE = "${params.K8S_NAMESPACE}"
    PULL_IMAGE_SECRET = "${params.K8S_PULLIMAGE_SECRET}"
    JWT_TOKEN = "${params.JWT_TOKEN}"
    JWT_PRIVKEY = "${params.JWT_PRIVKEY}"
    JDBC_URL = "${params.JDBC_URL}"
    JDBC_USER = "${params.JDBC_USER}"
    JDBC_PASSWORD = "${params.JDBC_PASSWORD}"
    REDIS_SERVER = "${params.REDIS_SERVER}"
    REDIS_PASSWORD = "${params.REDIS_PASSWORD}"
    REDIS_DB = "${params.REDIS_DB}"
    CONFIG_URL = "${params.CONFIG_URL}"
    XEAI_URL = "${params.XEAI_URL}"
    INITIAL_USERNAME = "${params.INITIAL_USERNAME}"
    INITIAL_PASSWORD = "${params.INITIAL_PASSWORD}"
  }
  stages {
    stage('Build') {
      steps {
        container ('maven') {
          withCredentials([usernamePassword(passwordVariable: 'DPCTL_PASSWORD', usernameVariable: 'DPCTL_USERNAME' , credentialsId : "$REPO_SECRET" ,)]) {
            sh 'chmod +x ${WORKSPACE}/.workflow/build.sh && ${WORKSPACE}/.workflow/build.sh'
          }
        }
      }
    }
    stage('Publish') {
      steps {
        container ('maven') {
          sh 'chmod +x ${WORKSPACE}/.workflow/publish.sh && ${WORKSPACE}/.workflow/publish.sh'
        }
      }
    }
    stage('Deploy') {
      steps {
        container ('maven') {
          input(id: 'deploy-to-k8s', message: 'deploy-to-k8s?')
          withCredentials([kubeconfigFile(credentialsId : "$KUBECONFIG_CREDENTIAL_ID" ,variable : "KUBECONFIG" ,)]) {
            sh 'chmod +x ${WORKSPACE}/.workflow/deploy.sh && ${WORKSPACE}/.workflow/deploy.sh'
          }
        }
      }
    }
  }
}